// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using blazorPWAEcommerce.Server.Data;

#nullable disable

namespace blazorPWAEcommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220219222313_ProductSeeding")]
    partial class ProductSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("blazorPWAEcommerce.Shared.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"), 1L, 1);

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            ProductDescription = "The Hitchhiker's Guide to the Galaxy",
                            ProductName = "The Hitchhiker's Guide to the Galaxy",
                            ProductPrice = 9.99m,
                            ProductUrl = "/images/H2G2_UK_front_cover.jpg"
                        },
                        new
                        {
                            ProductID = 2,
                            ProductDescription = "Ready Player One is a 2018 American science fiction adventure film based on Ernest Cline's novel of the same name. Directed by Steven Spielberg.",
                            ProductName = "Ready Player One",
                            ProductPrice = 19.99m,
                            ProductUrl = "/images/Ready_Player_One_(film).png"
                        },
                        new
                        {
                            ProductID = 3,
                            ProductDescription = "Nineteen Eighty-Four (also stylised as 1984) is a dystopian social science fiction novel and cautionary tale written by English writer George Orwell",
                            ProductName = "",
                            ProductPrice = 29.99m,
                            ProductUrl = "/images/1984first.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
